### ISSUE TITLE
Breaks core tab restore function

### ISSUE THREAD

**Issue by martinfinke** [k2b6s9j/formatter-clang-format#1]
When I enable this package, Atom's core functionality to restore the previously open tabs of a project/folder doesn't work anymore. When I disable it, it's working again.

Atom 1.0.2, OS X 10.10

**Comment by artagnon** [comment]
Are you sure about this (is it still applicable)? I Cmd-Shift-T all the time, and this plugin is enabled for me.

**Comment by keplersj** [comment]
That's all there confirmation I need to close this.
